baseurl = "/"
languageCode = "en-us"
theme = "core"
paginate = 5

[params]
  # dir name of your blog content (default is `content/posts`)
  contentTypeName = "posts"
  # "light" or "dark"
  defaultTheme = "dark"
  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 4
  # Show reading time in minutes for posts
  showReadingTime = true

  homeSubtitle = "Computer Science @ Stanford, Researcher, and Journalist."

  # social icons
  [[params.social]]
    name = "twitter"
    url  = "https://twitter.com/euirim"

  [[params.social]]
    name = "email"
    url  = "mailto:euirim@cs.stanford.edu"

  [[params.social]]
    name = "github"
    url  = "https://github.com/euirim"

  [[params.social]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/euirim"

[languages]
  [languages.en]
    title = "Euirim Choi"
    subtitle = "Student, Researcher, Journalist"
    keywords = "Euirim Choi, UChicago, Chicago Maroon, Computer Science"
    copyright = ""
    menuMore = "Show more"
    writtenBy = "By"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    newerPosts = "Newer posts"
    olderPosts = "Older posts"
    minuteReadingTime = "min read"
    dateFormatSingle = "January 2, 2006"
    dateFormatList = "January 2, 2006"

    [languages.en.params.logo]
      logoText = "Euirim"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "publications"
        name = "Publications"
        url = "#publications"
      [[languages.en.menu.main]]
        identifier = "projects"
        name = "Projects"
        url = "#projects"
      [[languages.en.menu.main]]
        identifier = "clips"
        name = "Clips"
        url = "#clips"